CREATE TABLE "BOARD"
(ID NUMBER(4) PRIMARY KEY
,BTITLE VARCHAR2(100)
,CONTENT    VARCHAR2(4000)
,"SYSDATE"    DATE
);

COMMIT;

DESC "BOARD";

CREATE SEQUENCE BOARD_SEQ
INCREMENT BY 1
START WITH 1
MINVALUE 1
MAXVALUE 1027;

INSERT INTO "BOARD"(ID) VALUES(BOARD_SEQ.NEXTVAL);

COMMIT;

insert into board
(id,btitle,content)
values (2,'가제','그냥');

commit;

create or replace trigger trg_b
BEFORE
INSERT ON BOARD
REFERENCING NEW AS NEW OLD AS OLD
FOR EACH ROW
BEGIN
SELECT BOARD_SEQ.NEXTVAL INTO:NEW.ID FROM DUAL;
END;

--UPDATE BOARD
--SET BTITLE = #{btitle},
--    CONTENT = #{content}
--WHERE ID = #{id}

--Delete from 테이블명
--where 조건;
