create table board(
	id bigint generated by default as identity,
	title varchar(30),
	writer varchar(20),
	content varchar(200),
	regdate date
  primary key(id)
);
insert into board(title) values('spring')
insert into board (writer) values ('java')
